config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection { post :import }
  end
  
  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'update_userinformation'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'confirmation_show'
      #勤怠変更
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_worktime_approval'
      patch 'attendances/update_worktime_approval'
      get 'working_employee'
      #所属長承認
      patch 'update_month_apply'
      get 'attendances/edit_month_approval'
      patch 'attendances/update_month_approval'
      #残業申請
      get 'attendances/edit_overwork_request'
      patch 'attendances/update_overwork_request'
      get 'attendances/edit_overwork_approval'
      patch 'attendances/update_overwork_approval'
  end
  resources :attendances, only: :update
  end
  resources :bases do
  end
  resources :attendancelogs do
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。¥
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :employee_number, length: { maximum: 10 }, allow_blank: true, uniqueness: true 
  validates :affiliation, length: { in: 2..10 }, allow_blank: true
  validates :uid, length: { maximum: 10 }, allow_blank: true, uniqueness: true 
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  #CSVインポート
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end

  # CVS更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", 
    "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  require 'csv'

  before_action :set_user, only: %i(show edit update update_userinformation destroy edit_basic_info update_basic_infos update_month_apply confirmation_show)
  before_action :logged_in_user, only: %i(show edit update destroy edit_basic_info update_basic_info)
  before_action :correct_user, only: %i(show edit)
  before_action :admin_user, only: %i(index update_userinformation destroy working_employee edit_basic_info update_basic_info)
  before_action :not_admin_user, only: %i(show confirmation_show)
  before_action :correct_superior_user, only: %i(confirmation_show)
  before_action :set_one_month, only: %i(show confirmation_show)
  before_action :superior_choice, only: %i(show confirmation_show)
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'アカウント作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    #CSV出力
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendances_csv(@attendances)
      end
    end 

    @approval = @user.attendances.find_by(worked_on: @first_day)
    @worked_sum = @attendances.where.not(started_at: nil).count  
    #申請お知らせ
    @approval_sum1 = Attendance.where(month_check_superior: "上長A", month_status: "申請中").count
    @approval_sum2 = Attendance.where(month_check_superior: "上長B", month_status: "申請中").count
    @approval_sum3 = Attendance.where(worktime_check_superior: "上長A", worktime_approval: "申請中").count
    @approval_sum4 = Attendance.where(worktime_check_superior: "上長B", worktime_approval: "申請中").count 
    @approval_sum5 = Attendance.where(superior_confirmation: "上長A", overwork_status: "申請中").count
    @approval_sum6 = Attendance.where(superior_confirmation: "上長B", overwork_status: "申請中").count
  end
  
  def confirmation_show
    @approval = @user.attendances.find_by(worked_on: @first_day)
    @worked_sum = @attendances.where.not(started_at: nil).count  
    #申請お知らせ
    @approval_sum1 = Attendance.where(month_check_superior: "上長A", month_status: "申請中").count
    @approval_sum2 = Attendance.where(month_check_superior: "上長B", month_status: "申請中").count
    @approval_sum3 = Attendance.where(worktime_check_superior: "上長A", worktime_approval: "申請中").count
    @approval_sum4 = Attendance.where(worktime_check_superior: "上長B", worktime_approval: "申請中").count 
    @approval_sum5 = Attendance.where(superior_confirmation: "上長A", overwork_status: "申請中").count
    @approval_sum6 = Attendance.where(superior_confirmation: "上長B", overwork_status: "申請中").count  
  end
  
  #所属長承認申請
  def update_month_apply
    @attendance = @user.attendances.find_by(worked_on: params[:user][:apply_month])
    if params[:user][:month_check_superior].present?
      @attendance.month_status = "申請中"
      @attendance.update_attributes(month_params)
      flash[:success] = "所属長承認申請が完了しました。"
    else
      flash[:danger] = "所属長を選択して下さい。"
    end
    redirect_to user_url(date: params[:date]) 
  end  
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
  end

  def update_userinformation
    if @user.update_attributes(userinformation_params)
      flash[:success] = "#{@user.name}のアカウント情報を更新しました。"
    elsif
      userinformation_params[:name].blank?
      flash[:danger] = "名前が入力されていません。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")  
    end
    redirect_to users_path
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  #CSVインポート
  def import
    # fileはtmpに自動で一時保存される
    if User.import(params[:file])
      flash[:success] = 'インポートしました。'
    else
      flash[:danger] = "インポート失敗しました。"
    end
    redirect_to users_url
  end
  
  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  def working_employee
    @users = User.all.includes(:attendances)
  end
  
  # 勤怠csv出力
  def send_attendances_csv(csv_attendances)
    csv_data = CSV.generate(headers: true) do |csv|
      header = ["日付", "出社時間", "退社時間", "備考"]
      # 表のカラム名を定義
      csv << header
      # column_valuesに代入するカラム値を定義
      csv_attendances.each do |attendance|
        
        values = [attendance.worked_on,
          attendance.before_started_at.present? && attendance.worktime_check_superior.blank? || attendance.worktime_approval.try(:include?, "承認") ? attendance.before_started_at.strftime("%H:%M") : nil,
          attendance.before_finished_at.present? && attendance.worktime_check_superior.blank? || attendance.worktime_approval.try(:include?, "承認") ? attendance.before_finished_at.strftime("%H:%M") : nil,
          
          if attendance.worktime_approval.try(:include?, "承認") 
            attendance.note
          else
            nil
          end
        ]
        # 表の値を定義
        csv << values
      end
    end
    send_data(csv_data, filename: "【勤怠表】#{User.find(params[:id]).name}#{Time.zone.now.strftime("(%Y年%m月)")}.csv")
  end
   
   
   
   
   
   
   
   
   
   private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    #1ヶ月申請
    def month_params
      params.require(:user).permit(:month_check_superior)
    end  
    
    def userinformation_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_user.html.erb
<%= form_with(model: user, url: update_userinformation_user_path(user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  
    <%= f.label :email, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :affiliation, class: "label-#{yield(:class_text)} form-label" %> 
    <%= f.text_field :affiliation, class: "form-control" %>

    <%= f.label :employee_number, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.text_field :employee_number, class: "form-control" %>

    <%= f.label :uid, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.text_field :uid, class: "form-control" %>
  
    <%= f.label :basic_work_time, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.time_field :basic_work_time, class: "form-control" %>
  
    <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)} form-label" %> 
    <%= f.time_field :designated_work_start_time, class: "form-control" %>

    <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)} form-label" %> 
    <%= f.time_field :designated_work_end_time, class: "form-control" %>

    <%= f.label :password, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.password_field :password, class: "form-control" %>
    
    <%= f.label :password_confirmation, class: "label-#{yield(:class_text)} form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  </div>
<% end %>

app/views/users/confirmation_show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table" id="attendance-time">
   <tr>
     <td>
     <% unless current_user?(@user) %>
       <div>
　　　   <%= l(@first_day, format: :middle) %> 時間管理表 
       </div>
     <% else %>
       <div class="btn-users-show"><%= link_to "⬅️", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
　　　   <%= l(@first_day, format: :middle) %> 時間管理表 
　　　   <%= link_to "➡️", user_path(date: @first_day.next_month), class: "btn btn-info" %>
       </div>
     <% end %> 
     </td>
         <td>
             指定勤務開始時間 : <%= format_basic_info(@user.designated_work_start_time) %>
         <br>    
             指定勤務終了時間 : <%= format_basic_info(@user.designated_work_end_time) %> 
         </td>
         <td colspan="3">基本時間 : <%= format_basic_info(@user.basic_work_time) %></td>
         <td>初日 : <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属 : <%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名 : <%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.employee_number %></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>締め : <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<% if current_user.superior? %>  
  <div class="row">
    <div class="col-md-6">  
      <% if @user.id == 2 && current_user?(@user) %>
        <div>   
          <% if @approval_sum1 == 0 %>
            <font class="approval">【所属長承認申請のお知らせ】</font>
          <% else %>
            <font class="approval-1"><%= link_to "【所属長承認申請のお知らせ】", attendances_edit_month_approval_user_path, remote: true, :style=>"color:maroon;" %></font>
            <font class="box-1" color="maroon"><%= "#{@approval_sum1}件の通知があります" %></font>
          <% end %>
        </div>
      <% end %>
      <% if @user.id == 3 && current_user?(@user) %>
        <div>   
          <% if @approval_sum2 == 0 %>
            <font class="approval">【所属長承認申請のお知らせ】</font>  
          <% else %>
            <font class="approval-1"><%= link_to "【所属長承認申請のお知らせ】", attendances_edit_month_approval_user_path, remote: true, :style=>"color:maroon;" %></font>
            <font class="box-1" color="maroon"><%= "#{@approval_sum2}件の通知があります" %></font>
          <% end %>
        </div>
      <% end %>
  
      <% if @user.id == 2 && current_user?(@user) %>
        <div>
          <% if @approval_sum3 == 0 %>
            <font class="approval">【勤怠変更申請のお知らせ】</font>
          <% else %>
            <font class="approval-2"><%= link_to "【勤怠変更申請のお知らせ】", attendances_edit_worktime_approval_user_path, remote: true, :style=>"color:green;" %></font>
            <font class="box-2" color="green"><%= "#{@approval_sum3}件の通知があります" %></font>
          <% end %>
        </div>    
      <% end %>
      <% if @user.id == 3 && current_user?(@user) %>
        <div>
          <% if @approval_sum4 == 0 %>
            <font class="approval">【勤怠変更申請のお知らせ】</font>
          <% else %>
            <font class="approval-2"><%= link_to "【勤怠変更申請のお知らせ】", attendances_edit_worktime_approval_user_path, remote: true, :style=>"color:green;" %></font>
            <font class="box-2" color="green"><%= "#{@approval_sum4}件の通知があります" %></font>
          <% end %>
        </div>    
      <% end %>
  
      <% if @user.id == 2 && current_user?(@user) %>
        <div>  
          <% if @approval_sum5 == 0 %>  
            <font class="approval">【残業申請のお知らせ】</font>
          <% else %>
            <font class="approval-3"><%= link_to "【残業申請のお知らせ】", attendances_edit_overwork_approval_user_path, remote: true, :style=>"color:blue;" %></font>
            <font class="box-3" color="blue"><%= "#{@approval_sum5}件の通知があります" %></font>
          <% end %>
        </div>
      <% end %>
      <% if @user.id == 3 && current_user?(@user) %>
        <div>  
          <% if @approval_sum6 == 0 %>  
            <font class="approval">【残業申請のお知らせ】</font>
          <% else %>
            <font class="approval-3"><%= link_to "【残業申請のお知らせ】", attendances_edit_overwork_approval_user_path, remote: true, :style=>"color:blue;" %></font>
            <font class="box-3" color="blue"><%= "#{@approval_sum6}件の通知があります" %></font>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>  
  <br>
<% end %>  
  
  <% if current_user?(@user) %>
    <div class="btn-users-show"><%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), 
      class: "btn btn-primary" %>
      <%= link_to "CSV出力", user_path(format: :csv, date: params[:date]), class: "btn btn-primary" %>
    <br>
      <%= link_to "勤怠修正ログ(承認済)", edit_attendancelog_path, class: "btn btn-primary", id: "btn-fix" %>
    </div>
    <br>
    <div>  
  <% end %>
  
<table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">

  <thead>
    <tr>
      <th rowspan="3">残業申請</th>
      <th rowspan="3">日付</th>
      <th rowspan="3">曜日</th>
      <th colspan="8">【実績】</th>
      <th colspan="5">所定外勤務</th>
    </tr>
    <tr>
      <th colspan="3">出社</th>
      <th colspan="3">退社</th>
      <th rowspan="2">存社時間</th>
      <th rowspan="2">備考</th>
      <th colspan="2">終了予定時間</th>
      <th rowspan="2">時間外時間</th>
      <th rowspan="2">業務処理内容</th>
      <th rowspan="2">指示者確認㊞</th>
    </tr>
    <tr>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
    </tr>
  </thead>

  <tbody>
    
    <% @attendances.each do |day| %>
    
    <tr>
      <td>
        <% if current_user?(@user) %> 
          <%= link_to "残業申請", attendances_edit_overwork_request_user_path(@user, date: day.worked_on), remote: true, class: "btn btn-primary" %>
        <% end %>
      </td>
      <td><%= l(day.worked_on, format: :short) %></td>
              <% 
                css_class = 
                case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
                when '土'
                'text-primary'
                when '日'
                'text-danger'
                end
              %>
      <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
      
      <td>
          <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" || day.worktime_approval == "否認" %>
            <%= day.started_at&.strftime("%H") %>
          <% else %>
            <%= day.before_started_at&.strftime("%H") %>
          <% end %>
      </td>
      
      <td>
          <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" || day.worktime_approval == "否認" %>
            <%= day.started_at&.strftime("%M") %>
          <% else %>
            <%= day.before_started_at&.strftime("%M") %>
          <% end %>
      </td> 
      
      <td>
          <% if current_user?(@user) %>
            <% if current_user?(@user) == day.started_at.nil? %> 
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          <% end %>
      </td>
      
      <td>
          <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" || day.worktime_approval == "否認" %>
            <%= day.finished_at&.strftime("%H") %>
          <% else %>
            <%= day.before_finished_at&.strftime("%H") %>
          <% end %>
      </td>
      <td>
          <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" || day.worktime_approval == "否認" %>
            <%= day.finished_at&.strftime("%M") %>
          <% else %>
            <%= day.before_finished_at&.strftime("%M") %>
          <% end %>  
      </td>
      
      <td>
          <% if current_user?(@user) %>
            <% if current_user?(@user) == day.started_at.present? %> 
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          <% end %>
      </td>
      
      <td>
          <% if day.started_at.present? && day.finished_at.present? %>      
            <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.tomorrow) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% elsif day.worktime_approval == "否認" %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.tomorrow) %>     
            <% else %>  
              <%= str_times = before_working_times(day.before_started_at.floor_to(15.minutes), day.before_finished_at.floor_to(15.minutes), day.tomorrow) %>   
            <% end %>
          <% end %>
      </td>
      <td>
          <% if day.worktime_approval == "申請中" || day.worktime_approval == "承認" || day.worktime_approval == "否認" %>
            <%= day.note %>
          <% else %>
            <%= day.before_note %>
          <% end %>
      </td>
      
      <!--%残業申請 %-->
      <td>
          <% if day.overwork_status == "申請中" || day.overwork_status == "承認" || day.overwork_status == "否認" %>
            <%= day.plans_endtime&.strftime('%H') %></td> 
          <% else %>
            <%= day.approval_overtime&.strftime('%H') %></td>  
          <% end %>
      <td>
          <% if day.overwork_status == "申請中" || day.overwork_status == "承認" || day.overwork_status == "否認" %>
            <%= day.plans_endtime&.strftime('%M') %></td> 
          <% else %>
            <%= day.approval_overtime&.strftime('%M') %></td>  
          <% end %>
      <td>
          <% if day.plans_endtime.present? %>
            <% if day.overwork_status == "申請中" || day.overwork_status == "承認" || day.overwork_status == "否認" %>
              <%= overwork_times(format_basic_info(day.plans_endtime), format_basic_info(@user.designated_work_end_time), day.next_day) %>
            <% else %> 
              <%= approval_times(format_basic_info(day.approval_overtime), format_basic_info(@user.designated_work_end_time), day.next_day) %>
            <% end %>
          <% end %>
      </td>
      
      <td>
          <% if day.overwork_status == "申請中" || day.overwork_status == "承認" || day.overwork_status == "否認" %>
            <%= day.business_contents %>
          <% else %>
            <%= day.approval_contents %>
          <% end %>
      </td>
    
      <td>
         <div class="approval">
         <% if day.worktime_check_superior? %>  
           <% if day.worktime_approval == "申請中" %> 
             <div class="worktime"><%= "【勤怠変更】#{day.worktime_check_superior}へ申請中" %></div>
           <% elsif day.worktime_approval == "承認" %>
             <div class="worktime"><%= "【勤怠変更】#{day.worktime_check_superior}：承認済" %></div>
           <% elsif day.worktime_approval == "否認" %> 
             <div class="worktime"><%= "【勤怠変更】#{day.worktime_check_superior}：否認" %></div>
           <% elsif day.worktime_approval == "なし" %>
               <div class="overwork"><%= "【残業申請】#{day.worktime_check_superior}：#{day.worktime_before_approval}" %></div>
           <% end %>
         <% end %> 

           <% if day.plans_endtime.present? %>
             <% if day.overwork_status == "申請中" %> 
               <div class="overwork"><%= "【残業申請】#{day.superior_confirmation}へ申請中" %></div>
             <% elsif day.overwork_status == "承認" %>
               <div class="overwork"><%= "【残業申請】#{day.superior_confirmation}：承認済" %></div>
             <% elsif day.overwork_status == "否認" %> 
               <div class="overwork"><%= "【残業申請】#{day.superior_confirmation}：否認" %></div>
             <% elsif day.overwork_status == "なし" %>
               <div class="overwork"><%= "【残業申請】#{day.superior_confirmation}：#{day.before_status}" %></div>
             <% end %>
           <% end %>
         </div>
      </td>
    </tr>
   </tbody>
     <% end %>
   <tfoot>
     <tr>
       <td></td>
       <td colspan="2"></td>
       <td colspan="6"></td>
       <td><%= format("%.2f", @total_working_times.to_f) %></td>
       <td colspan="5"></td>
       <td>
       
         <% if @approval.month_status == "承認" %>
           <font class="approval-4">所属長承認 &ensp; <%= "#{@approval.month_check_superior}：承認済" %></font>
         <% elsif @approval.month_status == "否認" %> 
           <font class="approval-4">所属長承認 &ensp; <%= "#{@approval.month_check_superior}：否認" %></font>
         <% elsif @approval.month_status == "申請中" %>
           <font class="approval-4">所属長承認 &ensp; <%= "#{@approval.month_check_superior}へ申請中" %></font>  
         <% else %>
           <font>所属長承認：未</font>  
         <% end %>
        
         <% if current_user == @user %> 
           <%= form_with(model: @user, url: update_month_apply_user_path(date: @first_day), local: true, method: :patch) do |f| %>
             <%= f.hidden_field :apply_month, :value => @first_day %>  
             <%= f.select :month_check_superior, @superiors.pluck(:name), { include_blank: "申請先を選択", selected: 1 },
                                                 { class: "form-control", required: true } %>
               <%= f.submit "申請", class: "btn btn-md btn-primary btn-block btn-monthapproval" %>
           <% end %>
         <% end %>
       </td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>ユーザー情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の修正") %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集') %>

<h1>基本情報の更新</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :basic_work_time, "基本勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_work_time, class: "form-control" %>
      
      <%= f.label :work_time, "指定勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>

      <div class="center">
        <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>