config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection { post :import }
  end
  
  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'update_userinformation'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'confirmation_show'
      #勤怠変更
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_worktime_approval'
      patch 'attendances/update_worktime_approval'
      get 'working_employee'
      #所属長承認
      patch 'update_month_apply'
      get 'attendances/edit_month_approval'
      patch 'attendances/update_month_approval'
      #残業申請
      get 'attendances/edit_overwork_request'
      patch 'attendances/update_overwork_request'
      get 'attendances/edit_overwork_approval'
      patch 'attendances/update_overwork_approval'
  end
  resources :attendances, only: :update
  end
  resources :bases do
  end
  resources :attendancelogs do
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  
  
  enum worktime_approval: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }, _prefix: true
  enum overwork_status: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }, _prefix: true
  
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :business_contents, length: { maximum: 50 }
  
  #出勤・退勤時間が存在しない場合無効
  validate :attendance_is_invalid_without_a_started_at_finished_at
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at

  # 退勤時間が存在しない場合、出勤時間は無効
  validate :started_at_is_invalid_without_a_finished_at
  
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  
  def attendance_is_invalid_without_a_started_at_finished_at
    if worktime_check_superior.present?
      errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.blank?
    end
  end 
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present? 
  end

  def started_at_is_invalid_without_a_finished_at
    if worktime_check_superior.present?
      errors.add(:finished_at, "が必要です") if finished_at.blank? && started_at.present?
    end
  end 
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?  
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at && tomorrow == false 
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  include AttendancesHelper

  before_action :set_user, only: %i(edit_one_month update_one_month update_month_apply edit_month_approval update_month_approval edit_overwork_request update_overwork_request
                                    edit_overwork_approval update_overwork_approval edit_worktime_approval update_worktime_approval attendance_log update_attendance_log) 
  before_action :logged_in_user, only: %i(update edit_one_month)
  before_action :correct_user, only: %i(edit_one_month edit_worktime_approval edit_overwork_request edit_overwork_approval edit_month_approval)
  before_action :not_admin_user, only: %i(edit_one_month)
  before_action :correct_superior_user, only: %i(edit_worktime_approval update_worktime_approval edit_month_approval update_month_approval edit_overwork_approval update_overwork_request)
  before_action :set_one_month, only: %i(edit_one_month update_one_month update_month_apply edit_overwork_request update_overwork_request)
  before_action :superior_choice, only: %i(edit_overwork_request edit_one_month)
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0), before_started_at: Time.current.change(sec: 0))
        flash[:info] = "出勤しました"
      end
    elsif @attendance.finished_at.nil? 
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0), before_finished_at: Time.current.change(sec: 0))
        flash[:info] = "退勤しました"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user 
  end
  
  def edit_one_month
  end

  #勤怠変更申請
  def update_one_month
    @application_count = 0    
    ActiveRecord::Base.transaction do  
      attendances_params.each do |id, item|   
        attendance = Attendance.find(id)
        if item[:worktime_check_superior].present?
          @application_count += 1  
          if item[:worktime_approval] = "申請中" 
            item[:approval_day] = @first_day
            attendance.update_attributes!(item)
          end   
        end         
      end
    end
    if @application_count > 0
      flash[:success] = "勤怠変更を申請しました。"
      #redirect_to user_url(date: params[:date])       
    end
    redirect_to user_url(date: params[:date]) 
  rescue ActiveRecord::RecordInvalid        
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end 
        
  #勤怠変更承認ページ
  def edit_worktime_approval
    @worktime_user = User.joins(:attendances).group("users.id").where(attendances: {worktime_check_superior: @user.name, worktime_approval: "申請中"})
    @worktime = Attendance.where(worktime_approval: "申請中", worktime_check_superior: @user.name).order(:worked_on)
  end
  
 #勤怠変更承認
  def update_worktime_approval
    worktime_approval_params.each do |id, item|
      attendance = Attendance.find(id)
      if params[:user][:attendances][id][:worktime_change] == "1" && params[:user][:attendances][id][:worktime_approval] == "申請中" 
      elsif params[:user][:attendances][id][:worktime_change] == "1" && params[:user][:attendances][id][:worktime_approval] == "承認" 
        if attendance.first_approval == 0 
          attendance.update_attributes(item.merge(before_started_at: attendance.started_at, before_finished_at: attendance.finished_at, change_started_at: attendance.before_started_at, change_finished_at: attendance.before_finished_at, 
                                                  before_note: attendance.note, approval_tomorrow: attendance.tomorrow, 
                                                  worktime_before_superior: attendance.worktime_check_superior, worktime_before_approval: "承認", first_approval: 1))
          flash[:success] = "勤怠変更申請処理が完了しました。"
        elsif attendance.first_approval == 1 
          attendance.update_attributes(item.merge(before_started_at: attendance.started_at, before_finished_at: attendance.finished_at,
                                       before_note: attendance.note, approval_tomorrow: attendance.tomorrow, 
                                       worktime_before_superior: attendance.worktime_check_superior, worktime_before_approval: "承認"))
          flash[:success] = "勤怠変更申請処理が完了しました。"
        end
      elsif params[:user][:attendances][id][:worktime_change] == "1" && params[:user][:attendances][id][:worktime_approval] == "否認" 
        attendance.update_attributes(item.merge(worktime_before_superior: attendance.worktime_check_superior, worktime_before_approval: "否認"))
        flash[:success] = "勤怠変更申請処理が完了しました。"
      elsif params[:user][:attendances][id][:worktime_change] == "1" && params[:user][:attendances][id][:worktime_approval] == "なし"
        attendance.update_columns(started_at: attendance.before_started_at, finished_at: attendance.before_finished_at, tomorrow: attendance.approval_tomorrow, note: attendance.before_note,
                                  worktime_check_superior: attendance.worktime_before_superior, worktime_approval: attendance.worktime_before_approval)
        flash[:success] = "勤怠変更申請処理が完了しました。"
      else
        #flash[:danger] = "変更する場合はチェックを入れてください。"
      end
    end
    redirect_to user_url(date: params[:date])
    return 
  end
    
  #所属長承認申請一覧ページ
  def edit_month_approval
    @attendances = Attendance.where(month_status: "申請中", month_check_superior: @user.name).order(:user_id).order(:worked_on).group_by(&:user_id)
  end
  
  #所属長申請処理
  def update_month_approval
    superior_approval_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:status_change] == "1" && item[:month_status] == "申請中"
      elsif item[:status_change] == "1" && item[:month_status] == "承認" 
        attendance.update_attributes(item)
        flash[:success] = "所属長申請処理が完了しました。"    
      elsif item[:status_change] == "1" && item[:month_status] == "否認" 
        attendance.update_attributes(item)
        flash[:success] = "所属長申請処理が完了しました。"
      elsif item[:status_change] == "1" && item[:month_status] == "なし" 
        attendance.update_attributes(item)
        flash[:success] = "所属長申請処理が完了しました。"
      else
      end
    end
    redirect_to user_url(date: params[:date])
  end

  #残業申請ページ
  def edit_overwork_request
    @attendances = @user.attendances.where(worked_on: params[:date])
  end 
 
  #残業申請
  def update_overwork_request
    overwork_request_params.each do |id, item| 
      attendance = Attendance.find(id)
      if item[:superior_confirmation].present?
        item[:overwork_status] = "申請中"
        attendance.update_attributes(item)
        flash[:success] = "残業申請が完了しました。"
      else
        flash[:danger] = "残業申請に失敗しました。"
      end
    end
    redirect_back(fallback_location: user_url)
  end

  #残業申請承認ページ
  def edit_overwork_approval
    @overwork_user = User.joins(:attendances).group("users.id").where(attendances: {superior_confirmation: @user.name, overwork_status: "申請中"})
    @overwork = Attendance.where(overwork_status: "申請中", superior_confirmation: @user.name).where.not(plans_endtime: nil).order(:worked_on)
  end
  
  #残業申請承認
  def update_overwork_approval
    overwork_approval_params.each do |id, item|
      attendance = Attendance.find(id)
        if params[:user][:attendances][id][:overwork_change] == "1" && params[:user][:attendances][id][:overwork_status] == "申請中"    
        elsif params[:user][:attendances][id][:overwork_change] == "1" && params[:user][:attendances][id][:overwork_status] == "承認"
          attendance.update_attributes(item.merge(approval_overtime: attendance.plans_endtime, approval_contents: attendance.business_contents, approval_next: attendance.next_day, 
                                                  before_superior: attendance.superior_confirmation, before_status: "承認"))
          flash[:success] = "残業申請処理が完了しました。"
        elsif params[:user][:attendances][id][:overwork_change] == "1" && params[:user][:attendances][id][:overwork_status] == "否認"
          attendance.update_attributes(item.merge(approval_overtime: attendance.plans_endtime, approval_contents: attendance.business_contents, approval_next: attendance.next_day, 
                                                  before_superior: attendance.superior_confirmation, before_status: "否認"))
          flash[:success] = "残業申請処理が完了しました。"
        elsif params[:user][:attendances][id][:overwork_change] == "1" && params[:user][:attendances][id][:overwork_status] == "なし"
          attendance.update_attributes(item.merge(plans_endtime: attendance.approval_overtime, next_day: attendance.approval_next, business_contents: attendance.approval_contents, 
                                       superior_confirmation: attendance.before_superior, overwork_status: attendance.before_status))
          flash[:success] = "残業申請処理が完了しました。"
        else  
          #flash[:danger] = "変更する場合はチェックを入れてください。"
        end      
    end
    redirect_to user_url
  end

  
  private
    #勤怠変更申請
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :tomorrow, :note, :worktime_check_superior, :worktime_approval, :first_approval])[:attendances]
    end
    
    #勤怠変更承認
    def worktime_approval_params 
      params.require(:user).permit(attendances: [:started_at, :finished_at, :worktime_approval, :worktime_change, :worktime_check_superior, :first_approval, :tomorrow])[:attendances]
    end

    #1ヶ月承認
    def superior_approval_params
      params.require(:user).permit(attendances: [:month_status, :status_change])[:attendances]
    end

    #残業申請
    def overwork_request_params
      params.require(:user).permit(attendances: [:plans_endtime, :next_day, :business_contents, :superior_confirmation, :overwork_status])[:attendances]
    end
    
    #残業申請承認
    def overwork_approval_params

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    return false
  end 

  def working_times(start, finish, tomorrow)
    unless tomorrow == true
      format("%.2f", (((finish - start) / 60) / 60.0))
    else
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)  
    end
  end
    
  def before_working_times(before_started_at, before_finished_at, tomorrow)
    unless tomorrow == true
      format("%.2f", (((before_finished_at - before_started_at) / 60) / 60.0))
    else
      format("%.2f", (((before_finished_at - before_started_at) / 60) / 60.0) + 24)  
    end
  end

  def worktime_tomorrow(finished_at, started_at, tomorrow)
    unless tomorrow == true
      format("%.2f", (finished_at.to_f - started_at.to_f)) 
    else
      format("%.2f", (finished_at.to_f - started_at.to_f) + 24) 
    end
  end

  def worktime_before_tomorrow(before_finished_at, before_started_at, tomorrow)
    unless tomorrow == true
      format("%.2f", (before_finished_at.to_f - before_started_at.to_f)) 
    else
      format("%.2f", (before_finished_at.to_f - before_started_at.to_f) + 24) 
    end
  end

  def overwork_times(plans_endtime, designated_work_end_time, next_day)
    unless next_day == true
      format("%.2f", (plans_endtime.to_f - designated_work_end_time.to_f)) 
    else
      format("%.2f", (plans_endtime.to_f - designated_work_end_time.to_f) + 24) 
    end
  end 

  def approval_times(approval_overtime, designated_work_end_time, next_day)
    unless next_day == true
      format("%.2f", (approval_overtime.to_f - designated_work_end_time.to_f)) 
    else
      format("%.2f", (approval_overtime.to_f - designated_work_end_time.to_f) + 24) 
    end
  end 

  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end
end

app/views/attendances/_edit_month_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>

  <%= form_with(model: @user, url: attendances_update_month_approval_user_path(date: @first_day), method: :patch, local: true) do |f| %>

    <% @attendances.each do |user_id, attendances| %>
      <% user = User.find(user_id) %> 
      <h1>【<%= user.name %>からの1ヶ月勤怠変更申請】</h1>
      
      <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
        <thead>
          <tr>
            <th>月</th>
            <th>指示者確認㊞</th>
            <th>変更</th>
            <th>勤怠を確認する</th>
          </tr>
       </thead>
       <% attendances.each do |day| %>
         <%= f.fields_for "attendances[]", day do |approval| %>
           <tbody>
             <tr>
               <td><%= l(day.worked_on, format: :middle) %></td>
               <td><%= approval.select :month_status, ["なし", "申請中", "承認", "否認"], 
                                                      { include_blank: true }, class: "form-control" %></td>
               <td><%= approval.check_box :status_change, checked: day.new_record? %></td>
               <td><%= link_to "確認", confirmation_show_user_path(user, date: day.worked_on), class: "btn btn-sm btn-primary" %></td>
             </tr>
           </tbody>
         <% end %>
       <% end %>
      </table>
    <% end %>   
      <div class="center">
        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
        <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %> 
      </div>
  <% end %>  
</div>

app/views/attendances/_edit_overwork_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>

  <%= form_with(model: @user, url: attendances_update_overwork_approval_user_path(@user, @attendance), method: :patch, local: true) do |f| %>
　
  <% @overwork_user.each do |user| %>
    
      <h1>【<%= user.name %>からの残業申請】</h1>
    
  <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>終了予定時間</th>
        <th>指定勤務終了時間</th>
        <th>時間外時間</th>
        <th>業務処理内容</th>
        <th>指示者確認㊞</th>
        <th>変更</th>
        <th>勤怠を確認する</th>
      </tr>
     </thead>
         
       <% @overwork.each do |day| %>
         <%= f.fields_for "attendances[]", day do |overtime| %>  
           <% if day.user_id == user.id %>
              
             <% css_class = case $days_of_the_week[day.worked_on.wday]
      					when '土'
      						'text-primary'
      					when '日'
      						'text-danger'
      					end %>   
           
           <tbody> 
             <tr>
               <td><%= l(day.worked_on, format: :short) %></td> 
               <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td> 
               <td><%= l(day.plans_endtime, format: :time) %></td>
               <td><%= format_basic_info(@user.designated_work_end_time) %></td>
               <td>
                   <% if day.plans_endtime.present? %>
                     <%= overwork_times(format_basic_info(day.plans_endtime), format_basic_info(@user.designated_work_end_time), day.next_day) %>
                   <% end %>
               </td>
               <td><%= day.business_contents %></td>
               <td><%= overtime.select :overwork_status, Attendance.overwork_statuses.keys, {prompt: true}, { class: "form-control input-md", required: true } %></td>
               <td><%= overtime.check_box :overwork_change, checked: day.new_record? %></td>
               <td><%= link_to "確認", confirmation_show_user_path(user, date: day.worked_on.beginning_of_month), class: "btn btn-sm btn-primary" %></td>
             </tr>
           </tbody>
           <% end %>
         <% end %> 
      <% end %>
      </table>
   <% end %>   
      <div class="center">
        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
        <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %> 
      </div>
  <% end %>  
</div>

app/views/attendances/_edit_worktime_approval.html.erb
<% provide(:title, @user.name) %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>

  <%= form_with(model: @user, url: attendances_update_worktime_approval_user_path, method: :patch, local: true) do |f| %>
　　
  <% @worktime_user.each do |user| %>

      <h1>【<%= user.name %>からの勤怠変更申請】</h1>
  
  <table class="table table-bordered table-condensed table-hover table-striped" id="table-worktime-approval">
    <thead>
      <tr>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="4">変更前</th>
        <th colspan="4">変更後</th>
        <th rowspan="3">備考</th>
　　　　<th rowspan="3">指示者確認㊞</th>
　　　　<th rowspan="3">変更</th>
　　　　<th rowspan="3">勤怠を確認する</th>
      </tr>
      <tr>
        <th colspan="2">出社</th>
        <th colspan="2">退社</th>
        <th colspan="2">出社</th>
        <th colspan="2">退社</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
       
       <% @worktime.each do |day| %>     
         <%= f.fields_for "attendances[]", day do |worktime| %>  
           <% if day.user_id == user.id %> 
           
             <% css_class = case $days_of_the_week[day.worked_on.wday]
      					when '土'
      						'text-primary'
      					when '日'
      						'text-danger'
      					end %>   
           
           <tbody> 
             <tr>
               <td><%= l(day.worked_on, format: :short) %></td> 
               <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td> 
               
               <td><%= day.before_started_at&.strftime("%H") %></td>  
               <td><%= day.before_started_at&.strftime("%M") %></td>
               <td><%= day.before_finished_at&.strftime("%H") %></td>  
               <td><%= day.before_finished_at&.strftime("%M") %></td>
              
               <td><%= day.started_at&.strftime("%H") %></td>
               <td><%= day.started_at&.strftime("%M") %></td>
               <td><%= day.finished_at&.strftime("%H") %></td>
               <td><%= day.finished_at&.strftime("%M") %></td>
               
               <td><%= day.note %></td>
               <td><%= worktime.select :worktime_approval, Attendance.worktime_approvals.keys, {prompt: true}, { class: "form-control input-md", required: true } %></td>
               <td><%= worktime.check_box :worktime_change, checked: day.new_record? %></td>
               <td><%= link_to "確認", confirmation_show_user_path(user, date: day.approval_day), class: "btn btn-sm btn-primary" %></td>
             </tr>
           </tbody>
         <% end %>
       <% end %> 
      <% end %>
      </table>
   <% end %>   
      <div class="center">
        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
        <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %> 
      </div>
  <% end %>  
</div>

app/views/attendances/edit_month_approval.html.erb
<div>

  <%= form_with(model: @user, url: attendances_update_month_approval_user_path, method: :patch, local: true) do |f| %>

    <% @attendances.each do |user_id, attendances| %>
      <% user = User.find(user_id) %> 
      <h1><%= user.name %>からの1ヶ月勤怠変更申請</h1>
      
      <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
        <thead>
          <tr>
            <th>月</th>
            <th>指示者確認㊞</th>
            <th>変更</th>
            <th>勤怠を確認する</th>
          </tr>
       </thead>
       <% attendances.each do |day| %>
         <%= f.fields_for "attendances[]", day do |approval| %>
           <tbody>
             <tr>
               <td><%= "#{day.apply_month.mon}月" %></td> 
               <td><%= approval.select :month_status, ["申請中", "承認", "否認", "なし"], { include_blank: false, selected: 1 }, class: "form-control" %></td>
               <td><%= approval.check_box :status_change, {}, "true", "false" %></td>
               <td><%= link_to "確認", user_path(user, date: day.worked_on), class: "btn btn-sm btn-primary" %></td>
             </tr>
           </tbody>
         <% end %>
       <% end %>
      </table>
    <% end %>   
      <div class="center">
        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
      </div>
  <% end %>  
</div>

app/views/attendances/edit_month_approval.js.erb
$("#edit-month-approval").html("<%= escape_javascript(render 'edit_month_approval') %>");
$("#edit-month-approval").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  
  <div>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
        　<th>指示者確認㊞</th>
        </tr>
      </thead>

      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <!--%= attendance.hidden_field :worktime_approval, :value => "申請中" %-->

      <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
              
              <% css_class = case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
                  when '土'
                  'text-primary'
                  when '日'
                  'text-danger'
                  end %>
          
          <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
          
        <% if Date.current < day.worked_on %>
          <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
          <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
        <% else %>
          <td><%= attendance.time_field :started_at, class: "form-control" %></td>
          <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
        <% end %>
              
          <td><%= attendance.check_box :tomorrow, {}, "true", "false" %></td>
          <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= worktime_tomorrow(format_basic_info(day.finished_at), format_basic_info(day.started_at), day.tomorrow) %>
              <% elsif day.before_started_at.present? && day.before_finished_at.present? %>
                <%= worktime_before_tomorrow(format_basic_info(day.before_finished_at), format_basic_info(day.before_started_at), day.tomorrow) %>
              <% end %>
          </td>
          <td><%= attendance.text_field :note, class: "form-control" %></td>
          <td>
              <% if day.worktime_approval == "申請中" && day.worktime_check_superior == "上長A" %>
                <%= attendance.select :worktime_check_superior, @superiors.pluck(:name), 
                                      { include_blank: "申請先選択", selected: "上長A" }, { class: "form-control"} %>
              <% elsif day.worktime_approval == "申請中" && day.worktime_check_superior == "上長B" %>                                                     
                <%= attendance.select :worktime_check_superior, @superiors.pluck(:name), 
                                      { include_blank: "申請先選択", selected: "上長B" }, { class: "form-control"} %>
              <% else %>
                <%= attendance.select :worktime_check_superior, @superiors.pluck(:name), 
                                      { include_blank: "申請先選択", selected: "申請先選択" }, { class: "form-control"} %>  
              <% end %>
          </td>  
      </tr>
          <% end %>
        <% end %>
       </tbody>
     </table>
  </div>
  

  <div class="center">
    <%= f.submit "勤怠変更申請", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %> 
  </div>
    <% end %>

app/views/attendances/edit_overwork_approval.js.erb
$("#edit-overwork-approval").html("<%= escape_javascript(render 'edit_overwork_approval') %>");
$("#edit-overwork-approval").modal("show");

app/views/attendances/edit_overwork_request.js.erb
$("#edit-overwork-request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit-overwork-request").modal("show");

app/views/attendances/edit_worktime_approval.js.erb
$("#edit-worktime-approval").html("<%= escape_javascript(render 'edit_worktime_approval') %>");
$("#edit-worktime-approval").modal("show");